"""database init

Revision ID: df9cd4feb14c
Revises: 
Create Date: 2026-10-09 18:10:16.289781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9cd4feb14c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline_employees',
    sa.Column('airline_employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=34), nullable=False),
    sa.Column('last_name', sa.String(length=34), nullable=False),
    sa.Column('email', sa.String(length=124), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=False),
    sa.Column('employee_type', sa.String(), nullable=False),
    sa.CheckConstraint("employee_type IN ('support', 'admin', 'operations')", name='ck_employee_type_correct'),
    sa.PrimaryKeyConstraint('airline_employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('airports',
    sa.Column('icao', sa.String(length=4), nullable=False),
    sa.Column('iata', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('icao'),
    sa.UniqueConstraint('iata')
    )
    op.create_index(op.f('ix_airports_iata'), 'airports', ['iata'], unique=True)
    op.create_table('airport_staff',
    sa.Column('airport_staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=34), nullable=False),
    sa.Column('last_name', sa.String(length=34), nullable=False),
    sa.Column('email', sa.String(length=124), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('staff_type', sa.String(), nullable=False),
    sa.Column('assigned_airport_icao', sa.String(length=3), nullable=False),
    sa.CheckConstraint("staff_type IN ('gate', 'check-in')", name='ck_airport_staff_type_correct'),
    sa.ForeignKeyConstraint(['assigned_airport_icao'], ['airports.icao'], ),
    sa.PrimaryKeyConstraint('airport_staff_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('guests',
    sa.Column('guest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_employee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=34), nullable=False),
    sa.Column('last_name', sa.String(length=34), nullable=False),
    sa.Column('email', sa.String(length=124), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['airline_employee_id'], ['airline_employees.airline_employee_id'], ),
    sa.PrimaryKeyConstraint('guest_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_icao', sa.String(length=3), nullable=False),
    sa.Column('destination_icao', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['destination_icao'], ['airports.icao'], ),
    sa.ForeignKeyConstraint(['origin_icao'], ['airports.icao'], ),
    sa.PrimaryKeyConstraint('route_id'),
    sa.UniqueConstraint('origin_icao', 'destination_icao')
    )
    op.create_table('companions',
    sa.Column('companion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('passport_name', sa.String(length=38), nullable=False),
    sa.Column('passport_number', sa.String(length=9), nullable=False),
    sa.Column('passport_expiry', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('passport_issue_authority', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=0), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.CheckConstraint("sex IN ('M', 'F', 'X')", name='ck_sex_correct'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_status_correct'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.PrimaryKeyConstraint('companion_id')
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('repeat_type', sa.String(), nullable=False),
    sa.Column('repeats_on', sa.Integer(), nullable=False),
    sa.Column('repeat_time_utc', sa.Time(), nullable=False),
    sa.Column('repeat_frequency', sa.Integer(), nullable=False),
    sa.Column('shown_in_list', sa.Boolean(), nullable=False),
    sa.CheckConstraint("repeat_type IN ('daily', 'weekly', 'monthly')", name='ck_repeat_type_correct'),
    sa.CheckConstraint('end_date >= start_date', name='ck_end_date_start_date_correct'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=3), nullable=False),
    sa.Column('scheduled_departure_datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('datetime_created_utc', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'departed', 'cancelled')", name='ck_flight_status_correct'),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('datetime_booked', sa.DateTime(), nullable=False),
    sa.Column('payment_cleared', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('booking_seats',
    sa.Column('booking_seat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.companion_id'], ),
    sa.PrimaryKeyConstraint('booking_seat_id'),
    sa.UniqueConstraint('seat_id', 'booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_seats')
    op.drop_table('bookings')
    op.drop_table('flights')
    op.drop_table('services')
    op.drop_table('companions')
    op.drop_table('routes')
    op.drop_table('guests')
    op.drop_table('airport_staff')
    op.drop_index(op.f('ix_airports_iata'), table_name='airports')
    op.drop_table('airports')
    op.drop_table('airline_employees')
    # ### end Alembic commands ###
